# Generated by Django 4.0.5 on 2022-07-10 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelMangement', '0001_initial'),
        ('manageMenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='hotel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotelMangement.hotel'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_thumbnail',
            field=models.ImageField(editable=False, upload_to='items_thumbs/'),
        ),
    ]
