# Generated by Django 4.0.5 on 2022-07-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageMenu', '0002_menu_hotel_id_alter_menu_item_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='role',
            field=models.CharField(blank=True, choices=[('MainCategory', 'MainCategory'), ('SubCategory', 'SubCategory')], default='SubCategory', max_length=100, null=True),
        ),
    ]
