# Generated by Django 4.0.5 on 2022-07-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageMenu', '0003_menu_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='role',
            new_name='category',
        ),
    ]
