# Generated by Django 4.0.5 on 2022-07-13 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('manageMenu', '0004_rename_role_menu_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='item_description',
            new_name='menu_description',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='item_name',
            new_name='menu_name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='item_image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='item_offer_price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='item_thumbnail',
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('submenu_name', models.CharField(blank=True, max_length=100, null=True)),
                ('submenu_description', models.CharField(blank=True, max_length=100, null=True)),
                ('menu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manageMenu.menu')),
            ],
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(blank=True, choices=[('MainCategory', 'MainCategory'), ('SubCategory', 'SubCategory')], default='SubCategory', max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_price', models.CharField(blank=True, max_length=100, null=True)),
                ('item_description', models.CharField(blank=True, max_length=100, null=True)),
                ('item_offer_price', models.CharField(blank=True, max_length=100, null=True)),
                ('item_image', models.ImageField(default='', null=True, upload_to='itemImage/')),
                ('item_thumbnail', models.ImageField(editable=False, upload_to='items_thumbs/')),
                ('is_veg', models.BooleanField(default=False)),
                ('sub_menu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manageMenu.submenu')),
            ],
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
